export enum TradeType {
  MASON = 'MASON',
  CARPENTER = 'CARPENTER',
  PLUMBER = 'PLUMBER',
  ELECTRICIAN = 'ELECTRICIAN',
  PAINTER = 'PAINTER',
  HELPER = 'HELPER',
  TILER = 'TILER',
  WELDER = 'WELDER',
  DRIVER = 'DRIVER',
  LABOUR = 'LABOUR',
  OTHER = 'OTHER',
}