import { Inject } from '@nestjs/common';
import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { ProjectPhase } from '../../../../domain/entities/project-phase.entity';
import { PROJECT_PHASE_REPOSITORY } from '../../../../domain/repositories/project-phase/project-phase-repository.interface';
import { IProjectPhaseWriter } from '../../../../domain/repositories/project-phase/project-phase.writer.interface';
import { CreateProjectPhaseCommand } from '../../../commands/project/create-project-phase.command';
import { ProjectPhaseDto } from '../../../dto/project/phase/project-phase.dto';
import { ProjectPhaseMapper } from '../../../mappers/project-phase.mapper';

@CommandHandler(CreateProjectPhaseCommand)
export class CreateProjectPhaseHandler implements ICommandHandler<CreateProjectPhaseCommand> {
  constructor(
    @Inject(PROJECT_PHASE_REPOSITORY)
    private readonly projectPhaseWriter: IProjectPhaseWriter,
  ) {}

  async execute(command: CreateProjectPhaseCommand): Promise<ProjectPhaseDto> {
    const { dto } = command;

    // Create domain entity
    // convert incoming strings to Date objects where appropriate
    const plannedStart = dto.plannedStartDate
      ? new Date(dto.plannedStartDate)
      : null;
    const plannedEnd = dto.plannedEndDate ? new Date(dto.plannedEndDate) : null;

    const phase = new ProjectPhase(
      '', // ID will be generated by DB
      dto.projectId!,
      dto.name,
      dto.description || null,
      0, // progress default
      plannedStart,
      plannedEnd,
      null, // actual start
      null, // actual end
      'Not Started', // Default status
      dto.sequence,
      new Date(),
      new Date(),
      [], // initial workerGroups
      dto.workerGroupIds || [],
    );

    const saved = await this.projectPhaseWriter.save(phase);
    return ProjectPhaseMapper.toDto(saved);
  }
}
