import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { Inject } from '@nestjs/common';
import { MaterialRequestDto } from '../../../dto/material/request.dto';
import {
  MaterialRequest,
  MaterialRequestItem,
} from '../../../../domain/entities/material-request.entity';
import { MaterialRequestMapper } from '../../../mappers/material-request.mapper';
import { CreateMaterialRequestCommand } from '../../../commands/material/create-material-request.command';
import {
  IMaterialRequestWriter,
  MATERIAL_REQUEST_WRITER,
} from '../../../../domain/repositories/project-material/material-request.writer.interface';
import { MaterialRequestStatus } from '../../../../domain/enums/material-request-status.enum';
import { MaterialRequestPriority } from '../../../../domain/enums/material-request-priority.enum';

@CommandHandler(CreateMaterialRequestCommand)
export class CreateMaterialRequestHandler implements ICommandHandler<CreateMaterialRequestCommand> {
  constructor(
    /**
     * DIP — injects only the writer interface via Symbol token.
     * Command handlers must never see read or query operations.
     */
    @Inject(MATERIAL_REQUEST_WRITER)
    private readonly repository: IMaterialRequestWriter,
  ) {}

  async execute(
    command: CreateMaterialRequestCommand,
  ): Promise<MaterialRequestDto> {
    const { userId, dto } = command;

    const request = new MaterialRequest(
      '', // ID generated by the database
      `REQ-${Date.now()}`,
      dto.projectId,
      userId,
      dto.items.map(
        (i) =>
          new MaterialRequestItem(
            i.materialId,
            i.materialName,
            i.quantity,
            i.unit,
          ),
      ),
      dto.priority ?? MaterialRequestPriority.MEDIUM,
      dto.purpose ?? null,
      dto.deliveryLocation ?? null,
      dto.requiredDate,
      MaterialRequestStatus.PENDING,
      null,
      null,
      null,
      null,
      new Date(),
      new Date(),
    );

    const created = await this.repository.save(request);
    return MaterialRequestMapper.toDto(created);
  }
}
